### ISSUE TITLE
arm_wells and tastypie don't play well together

### ISSUE THREAD

**Issue by niran** [armstrong/armstrong#37] opened 2011-11-03 03:25 UTC
Tastypie calls filter on querysets. arm_wells's `GenericForeignKeyQuerySet` doesn't have a filter method. We have options:
1. Find a way to get tastypie to avoid calling filter.
2. If tastypie passes no arguments to filter when the request doesn't require filtering, add a filter method to `GenericForeignKeyQuerySet` that returns `self` if the arguments are empty and raises an exception otherwise.
3. If tastypie is passing arguments to filter, things get more complicated. Perhaps an argument to the queryset constructor that makes filter return self regardless to avoid errors?

**Comment by dmclain** [comment] 2011-11-07 17:34
We do somewhat better now after armstrong/armstrong.core.arm_wells#10 was merged and released in 1.2.0. It looks like master on tastypie has some hooks that will make life better, but in the meantime there's extensive use of filter/order_by/etc and unless we want to make these querysets actually implement all of that we're just not going to be able to play well with tastypie.

**Comment by tswicegood** [comment] 2012-04-24 17:04
Is this still an issue?

**Comment by dmclain** [comment] 2012-04-24 21:29
Yes, the basic issue is that MergeQueryset doesn't support filtering. We could I suppose pass through the filter to both of the querysets, though that might still explode in the case of wells since one of the querysets would be a GenericForeignKeyQueryset, which can't support filtering.

**Comment by niran** [comment] 2012-04-24 22:41
Don't you think it would still be useful to turn `filter()` with no args into `_clone()`? I think stuff is breaking that isn't actually necessary. Basic API calls don't filter anything.

**Comment by tswicegood** [comment] 2012-04-25 13:09
Do we have a list of ways tastypie calls `filter`?  It seems like supporting the no-args way is trivial and something we should do, but if that's not the way tastypie calls things, then I don't know how useful it'd actually be.

**Comment by dmclain** [comment] 2012-04-25 18:28
We don't know all the different ways that tastypie can call filter, but we added empty filters in https://github.com/armstrong/armstrong.core.arm_wells/commit/e3c837bd991f4fe87c3ebb9e9e971e9570bd33f2

**Comment by tswicegood** [comment] 2012-04-25 18:32
Cool.  If we don't have a use case that we can reproduce this bug, I'm going to assume this issue was opened prior to that code be introduced and close it.  We'll re-open this if there is a reproducible use case.

**Closed as completed by tswicegood** 2012-04-25 18:32 UTC
Labels: bugs, core.arm_wells
