### ISSUE TITLE
Use markdown for all TextFields

### ISSUE THREAD

**Issue by epicserve** [armstrong/armstrong#57] opened 2012-04-10 20:42 UTC
I've found that using markdown for textfields is much more versatile than using HTML because you can easily convert markdown to other formats (i.e. PDF, Plain Text, etc.). Also, the content ends up being a lot more clean than if you allow or use an HTML editor. There is also a nice Markdown editor that you can add to your TextFields that makes adding content easier for the non-techie people who are adding the content. The following screenshot shows the [WMD](http://code.google.com/p/wmd/) markdown editor (it looks like the newest version of WMD is now [PageDown](http://code.google.com/p/pagedown/)).  I think I would actually prefer to have the preview be a toggle like Github uses for their issue tracker textarea, rather than bellow the textarea field like I have it in the screenshot.

![Markdown Editor](http://f.cl.ly/items/1s08403T3h2e1z2O0V2H/Screen%20Shot%202012-04-10%20at%201.25.34%20PM.png)

**Comment by tswicegood** [comment] 2012-04-11 00:25
I'm with you on this one, but it's a no-go as the default.  Making the default for the news room Markdown (even MMD) just doesn't have any traction on our end.

That said, the text editor is something that is extremely flexible and something that can be configured site-wide for any models that opt-in to it.  You could use the current implementation of CKEditor as an example of how you could implement a custom editor that uses WMD.  I'm going to close this, but feel free to re-open it if you'd like to take a stab at implementing a custom editor.

As a side note, [this](http://jhollingworth.github.com/bootstrap-wysihtml5/) is where I'm hoping to take the editor over the next few months.  It's _so_ much better than the other editors that are out there.

**Closed as completed by tswicegood** 2012-04-11 00:25 UTC
Labels: wishlist, feature, hatband

**Comment by epicserve** [comment] 2012-04-11 16:05
I would hope that you would consider opening this up for discussion again. I know the you can use whatever text editor your want, so that being said, if the Textas Tribune's newsroom doesn't want the Markdown editor, why couldn't you guys switch it out for your preferred editor?

It seems like if you're with me on this one then, why don't we make Markdown the default and then if you don't like it, you can switch it out with something else? It seems like the default choice should be what developers believe is the right choice.

I know our newsroom wouldn't have any issue using Markdown as the default editor because this is very similar to the way Ellington does their editor. Also, there are [good articles](http://www.hiltmon.com/blog/2012/02/20/the-markdown-mindset/) out there that support this mindset.

**Comment by tswicegood** [comment] 2012-04-11 17:37
A couple of developers saying it's the right thing versus news rooms agreeing to learn a new mark up language are two different things.

The think the bigger issue here is that the current editors don't work -- they're hard to extend, they do weird stuff to the underlying HTML, and so on.  Markdown is a solution to the symptom -- HTML's verbosity for simple text.  I think a simple editor that provides hooks into the basic "formatting" (I use that word lightly -- bold, emphasis, links, and so on) is a much better solution.  As an added benefit, the markup that is used becomes an implementation detail so it wouldn't be unreasonable to store it in Markdown/MMD if that turns out to be a better solution.

**Comment by epicserve** [comment] 2012-04-11 17:48
The "implementation detail" could be handled using a simple django south data migration or something similar for any existing Armstrong instance that wants to start using Markdown going forward. This could also be handled like I handle it in my private CMS I use, where I support two markup languages. If you choose HTML it switches your editor to TinyMCE and if you choose Markdown it switches your editor to WMD. Here is a screenshot.

![Markup Language Select](http://f.cl.ly/items/0s0G2P411k2Y1l1J1E39/Screen%20Shot%202012-04-11%20at%2010.46.58%20AM.png)

**Comment by tswicegood** [comment] 2012-04-11 17:54
Yes, I agree that could definitely be done.  The issue is that I don't want to have to tell newsrooms that if they want to use the out-of-the-box configuration of Armstrong they have to learn a new markup language.  I'm open to a PR with an option that adds this as an editor (or better yet, make it a package by itself that's entirely independent), but I just don't see it as viable for the default.

**Comment by epicserve** [comment] 2012-04-11 17:58
**sigh** ... looks as if we've reached an impasse.

**Comment by dmclain** [comment] 2012-04-11 18:30
It's not really an impasse. We built the rich text editor code such that building an app that puts markdown in isn't that hard, especially if you already have a working markdown rich text widget. It just won't be the default editor that we ship with.

**Comment by epicserve** [comment] 2012-04-11 18:44
Dmclain, I've stated that I understand that you can switch out the default with whatever editor you want. It's an impasse because I would like to see Markdown as the default. I'm methodologically opposed to using HTML for content. In my experience using HTML for content has always come back to bite me in the butt in one way or another. I end up having to do way more support for users than when I go with Markdown. Read [The Markdown Mindset](http://www.hiltmon.com/blog/2012/02/20/the-markdown-mindset/), which does a good job explaining why Markdown is a good choice.

As I'm exploring Armstrong more and considering it for our paper, this is one of the areas in which the default of using an HTML editor makes a bad first impression with me and this is why I would like to see if the default could be changed so that others that might consider using and or getting involved with Armstrong would have a better first impression of it.
