### ISSUE TITLE
Error when installing from github and pip

### ISSUE THREAD

**Issue by rlander** [armstrong/armstrong#20] opened 2011-10-06 03:10 UTC
Hello developers!

I've tried to install Armstrong multiple times in a separate and clean virtualenv and I always get the same error:

Caught TypeError while rendering: **init**() keywords must be strings

Not sure what's going on. Seems to be a a custom tag error, but I could not debug it.

Here's the full traceback:
http://dpaste.com/628463/

Thanks!

Rodrigo Landerdahl

**Comment by dmclain** [comment] 2011-10-06 05:05
Looks like the function we're using to parse tags (which is from django) creates dictionaries with unicode keys (see https://github.com/kylemacfarlane/django-cuddlybuddly-thumbnail/issues/5). It works in python 2.7.x, not sure what the lowest version of python we support is, but I thought it was 2.7. @tswicegood would know.

**Comment by rlander** [comment] 2011-10-06 06:35
That seems to be the problem indeed. I am using 2.6 so I'll try 2.7 tomorrow and let you know how it goes.

**Comment by tswicegood** [comment] 2011-10-06 13:55
Thanks for the report.  This does look like it's a bug on the Django side, but it looks like something we can possibly fix on our end.

That said, Python 2.7 is the official "yes, it works here" version for Armstrong.  We're trying to support 2.6.x as well, but we haven't gone out of our way.

**Comment by crccheck** [comment] 2011-10-06 19:11
I tried reproducing this on python 2.6.6 and couldn't. (I did get another error I'm going to try and look into deeper later)

**Comment by rlander** [comment] 2011-10-07 19:30
I installed Armstrong today on a fresh VM (ubuntu 11.4 / python 2.7.1) and it worked fine.

It's still not working on the original machines (ubuntu 9.10 and osx), though. I'll take a closer look this weekend.

BTW, why is there a separate CLI for armstrong, instead of manage.py commands?

**Comment by tswicegood** [comment] 2011-10-09 21:31
Hey @rlander: we've worked out what the problem is, but we haven't tracked down the specific version where the problem was introduced.  We have a fix in the works so it will work on the older versions of Python, but 2.7 is the official recommendation for Armstrong.

About `armstrong` instead of `manage.py`, that's a question better suited to the mailing list.

**Comment by rlander** [comment] 2011-10-10 19:05
Thanks for the update, @tswicegood. I'll send my question to the mailing list.

**Comment by dmclain** [comment] 2011-10-20 17:20
Closing this since it works as designed on 2.7

**Closed as completed by dmclain** 2011-10-20 17:20 UTC
Labels: bugs, core.arm_sections
